-- Schema Version 3
-- Description: Database schema v3 (Removed annotation_element_versions, and added trigger)


-- Drop tables in dependency order
DROP TABLE IF EXISTS annotation_element CASCADE;
DROP TABLE IF EXISTS screenshot CASCADE;
DROP TABLE IF EXISTS batch CASCADE;
DROP TABLE IF EXISTS taxonomy CASCADE;

------------------------------------------------------------
-- Taxonomy: shared label definitions for UI elements
------------------------------------------------------------
CREATE TABLE taxonomy (
    taxonomy_id BIGSERIAL PRIMARY KEY,
    taxonomy_label_name TEXT NOT NULL,       -- e.g., 'Button'
    taxonomy_description TEXT,               -- explanation/usage notes
    taxonomy_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

------------------------------------------------------------
-- Batch: groups of uploaded screenshots with performance data
------------------------------------------------------------
CREATE TABLE batch (
    batch_id BIGSERIAL PRIMARY KEY,
    batch_name TEXT NOT NULL,             -- batch name from the UI
    batch_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    batch_status TEXT NOT NULL CHECK (batch_status IN ('uploading', 'extracting', 'annotating', 'preview', 'done')),
    batch_analysis_type TEXT NOT NULL CHECK (batch_analysis_type IN ('Usability Audit', 'Conversion Analysis', 'UI Categorization')),
    batch_master_prompt_runtime NUMERIC,   -- in seconds
    batch_total_inference_time NUMERIC,    -- in seconds
    batch_detected_elements_count INTEGER, -- number of detected UI elements
    batch_description TEXT                 -- optional metadata
);

------------------------------------------------------------
-- Screenshot: individual UI images; file_url is generated by Supabase Storage
------------------------------------------------------------
CREATE TABLE screenshot (
    screenshot_id BIGSERIAL PRIMARY KEY,
    batch_id BIGINT NOT NULL,  -- renamed to match v2 foreign key naming
    screenshot_file_name TEXT NOT NULL,
    screenshot_file_url TEXT NOT NULL,         -- full public URL from Supabase Storage
    screenshot_processing_status TEXT NOT NULL CHECK (screenshot_processing_status IN ('pending', 'processing', 'completed', 'error')),
    screenshot_processing_time INTERVAL,       -- time taken to annotate this image
    screenshot_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_screenshot_batch
        FOREIGN KEY (batch_id)
        REFERENCES batch(batch_id)
        ON DELETE CASCADE
);

-- Index for better join performance on batch_id
CREATE INDEX idx_screenshot_batch_id ON screenshot(batch_id);

------------------------------------------------------------
-- Annotation Element: details for each UI element annotation
-- Denormalized table containing annotation metadata (including integrated versioning)
------------------------------------------------------------
CREATE TABLE annotation_element (
    annotation_element_id BIGSERIAL PRIMARY KEY,
    screenshot_id BIGINT NOT NULL, -- renamed to match v2 foreign key naming (was annotation_element_screenshot_id)
    annotation_element_version_number INTEGER NOT NULL DEFAULT 1,  -- version number (default 1, incremented for revisions)
    annotation_element_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    annotation_element_x_min NUMERIC NOT NULL,           -- x-coordinate (top-left)
    annotation_element_x_max NUMERIC NOT NULL,           -- for bounding box width
    annotation_element_y_min NUMERIC NOT NULL,           -- y-coordinate (top-left)
    annotation_element_y_max NUMERIC NOT NULL,           -- for bounding box height
    taxonomy_id BIGINT,               -- renamed to match v2 (was annotation_element_taxonomy_id)
    annotation_element_text_label TEXT,                  -- display text (from UI)
    annotation_element_description TEXT,                 -- additional element description
    annotation_element_inference_time NUMERIC NOT NULL,  -- detection time in seconds
    CONSTRAINT fk_annotation_element_screenshot
        FOREIGN KEY (screenshot_id)
        REFERENCES screenshot(screenshot_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_annotation_element_taxonomy
        FOREIGN KEY (taxonomy_id)
        REFERENCES taxonomy(taxonomy_id)
        ON DELETE SET NULL
);

-- Indexes for efficient lookups on foreign keys
CREATE INDEX idx_annotation_element_screenshot_id ON annotation_element(screenshot_id);
CREATE INDEX idx_annotation_element_taxonomy_id ON annotation_element(taxonomy_id);

------------------------------------------------------------
-- Function and Trigger to Automatically Set version_number
------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_annotation_version()
RETURNS TRIGGER AS $$
DECLARE
    current_max INTEGER;
BEGIN
    -- Only set version_number if it was not explicitly provided (or provided as 0)
    IF NEW.annotation_element_version_number IS NULL OR NEW.annotation_element_version_number = 0 THEN
        SELECT COALESCE(MAX(annotation_element_version_number), 0)
          INTO current_max
        FROM annotation_element
        WHERE screenshot_id = NEW.screenshot_id;
        NEW.annotation_element_version_number := current_max + 1;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_set_annotation_version
BEFORE INSERT ON annotation_element
FOR EACH ROW
EXECUTE FUNCTION set_annotation_version();
